;;;; package.lisp

(defpackage #:cellctl
  (:use #:cl)
  (:export
   #:MODEL-SLOT
   #:MODEL-ARRAY
   #:SET-CELL
   #:SET-CELL-HOOK
   #:REF-SET-CELL
   #:VALUE-CELL
   #:BANG-CELL
   #:MAP-FN
   #:RMAP-FN
   #:REF-SET-HOOK
   #:VAL
   #:SET-REF
   #:DEPENDENTS
   #:TRIGGER
   #:ACTION-FN
   ;;   #:MAP-FN
;;   #:RMAP-FN
   #:WITH-MODEL-SLOTS
   #:CLASS-REDEFINE-MODEL-SLOTS-SETF
   #:MODEL-SLOT-REGISTER-SETF-METHOD
   #:CLASS-GET-MODEL-SLOT-READERS
   #:CLASS-REDEFINE-MODEL-SLOT-ACCESSORS))
